### ISSUE TITLE
some questions about the paper...

### ISSUE THREAD

**Issue by fitzhu** [mrkoujan/DeepFaceFlow#1]
Hi, thanks to the great work first! And I have some questions about the paper.

1. The designed framework is marked by two main stages, 3DMeshReg and DFFNet. The 3DMeshReg is used to perdict 3D face model of the input face image, why need PNCC as input?

2. As mentioned above, the 3DMeshReg is used to perdict 3D face model of the input face image, if you obtained the 3D face, you can compute the 3D flow field, why do you need the DFFNet to predict 3D flow field?

Looking forward to your reply. Thanks : )

**Comment by mramikoujan** [comment]
Hey,

Thanks for your interest in our work.

The PNCC is used as an input to the DFFNet along with the pair of monocular input RGB images. The 3DMeshReg provides a rough estimation of the 3D face in the first image and it servers as a template while minimising our cost function formulated for training the DFFNet . Using this 3D mesh to directly predict the 3D flow by formulating an energy equation with photo-consistency error could work but practicaly is highly sensitive to capturing set-up of the images and not robust when dealing with in-the-wild images. Instead, we follow a data-driven approach and train another network on two large-scale datasets for this purpose.

I hope this has made it clear and answered your questions.

**Comment by fitzhu** [comment]
Very clear, thanks for your reply :)
